services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_MAPBOX_TOKEN: ${NEXT_PUBLIC_MAPBOX_TOKEN}
        NEXT_PUBLIC_MAPBOX_STYLE_ID: ${NEXT_PUBLIC_MAPBOX_STYLE_ID}
        NEXT_PUBLIC_MAPBOX_ADMIN_STYLE_ID: ${NEXT_PUBLIC_MAPBOX_ADMIN_STYLE_ID}
    env_file:
      - .env.local
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: production
      PORT: 3004
      HOSTNAME: 0.0.0.0
    network_mode: host
    restart: unless-stopped
